modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="assortedcuisine"
version="0.1.1"
displayName="Assorted Cuisine"
displayURL="https://lolcatz.de/assorted/cuisine"
credits="Grim3212 - Developer of the Grim Pack & Assorted Mods"
authors="junior_Feuerwolf / JuniorWMG"
description="Adds an random assortment of food items to your Minecraft world."

[[dependencies.assortedcuisine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.assortedcuisine]]
    modId="assorted-tools"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assortedcuisine]]
    modId="assorted-lib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assortedcuisine]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

